my_file=open('hellobc.txt')

print(my_file)
print(my_file.read())
my_file.close()
my_file=open('hellobc.txt')
print("ending of file here")
print("******************************")
print(my_file.readline())
print("******************************")
print("******************************")
print(my_file.readline())
print("******************************")
print("******************************")
print(my_file.readline())
print("******************************")
my_file.seek(0)
print(my_file.readlines())
